(define (problem ext3_10r_5h_10d_10)
  (:domain hotel-extensio3)
  (:requirements :typing :negative-preconditions :adl :fluents)

  (:objects
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    h1 h2 h3 h4 h5 - habitacio
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 - dia
  )

  (:init
    (= (total-reserves-descartades) 0)
    (= (total-places-descartades) 0)

    (= (capacitat h1) 1)
    (= (capacitat h2) 1)
    (= (capacitat h3) 3)
    (= (capacitat h4) 2)
    (= (capacitat h5) 2)

    (= (persones r1) 2)
    (= (persones r2) 1)
    (= (persones r3) 1)
    (= (persones r4) 4)
    (= (persones r5) 1)
    (= (persones r6) 1)
    (= (persones r7) 1)
    (= (persones r8) 2)
    (= (persones r9) 2)
    (= (persones r10) 1)

    (dies-reserva r1 d1)
    (dies-reserva r1 d2)
    (dies-reserva r1 d3)
    (dies-reserva r2 d5)
    (dies-reserva r2 d6)
    (dies-reserva r2 d7)
    (dies-reserva r2 d8)
    (dies-reserva r3 d5)
    (dies-reserva r3 d6)
    (dies-reserva r3 d7)
    (dies-reserva r4 d7)
    (dies-reserva r4 d8)
    (dies-reserva r4 d9)
    (dies-reserva r4 d10)
    (dies-reserva r5 d5)
    (dies-reserva r5 d6)
    (dies-reserva r5 d7)
    (dies-reserva r5 d8)
    (dies-reserva r6 d4)
    (dies-reserva r6 d5)
    (dies-reserva r7 d5)
    (dies-reserva r7 d6)
    (dies-reserva r7 d7)
    (dies-reserva r7 d8)
    (dies-reserva r8 d4)
    (dies-reserva r8 d5)
    (dies-reserva r9 d7)
    (dies-reserva r9 d8)
    (dies-reserva r9 d9)
    (dies-reserva r9 d10)
    (dies-reserva r10 d2)
    (dies-reserva r10 d3)
    (dies-reserva r10 d4)
    (dies-reserva r10 d5)
    (dies-reserva r10 d6)
  )

  (:goal (forall (?r - reserva) (processada ?r)))

  (:metric minimize (+ (* 10 (total-reserves-descartades)) (total-places-descartades)))
)
