(define (problem ext3_mid_10r_7h_15d_50)
  (:domain hotel-extensio3)
  (:requirements :typing :negative-preconditions :adl :fluents)

  (:objects
    r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 - reserva
    h1 h2 h3 h4 h5 h6 h7 - habitacio
    d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 - dia
  )

  (:init
    (= (total-reserves-descartades) 0)
    (= (total-places-descartades) 0)

    (= (capacitat h1) 7)
    (= (capacitat h2) 2)
    (= (capacitat h3) 2)
    (= (capacitat h4) 7)
    (= (capacitat h5) 4)
    (= (capacitat h6) 3)
    (= (capacitat h7) 3)

    (= (persones r1) 2)
    (= (persones r2) 1)
    (= (persones r3) 5)
    (= (persones r4) 1)
    (= (persones r5) 5)
    (= (persones r6) 4)
    (= (persones r7) 1)
    (= (persones r8) 1)
    (= (persones r9) 1)
    (= (persones r10) 2)

    (dies-reserva r1 d7)
    (dies-reserva r1 d8)
    (dies-reserva r1 d9)
    (dies-reserva r2 d11)
    (dies-reserva r2 d12)
    (dies-reserva r2 d13)
    (dies-reserva r2 d14)
    (dies-reserva r2 d15)
    (dies-reserva r3 d5)
    (dies-reserva r3 d6)
    (dies-reserva r4 d8)
    (dies-reserva r4 d9)
    (dies-reserva r4 d10)
    (dies-reserva r5 d6)
    (dies-reserva r5 d7)
    (dies-reserva r6 d6)
    (dies-reserva r6 d7)
    (dies-reserva r7 d7)
    (dies-reserva r7 d8)
    (dies-reserva r7 d9)
    (dies-reserva r7 d10)
    (dies-reserva r7 d11)
    (dies-reserva r8 d3)
    (dies-reserva r8 d4)
    (dies-reserva r8 d5)
    (dies-reserva r8 d6)
    (dies-reserva r9 d7)
    (dies-reserva r9 d8)
    (dies-reserva r10 d7)
    (dies-reserva r10 d8)
  )

  (:goal (forall (?r - reserva) (processada ?r)))

  (:metric minimize (+ (* 100 (total-reserves-descartades)) (total-places-descartades)))
)
